// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-directions/EditorialFinanceDashboard.tsx": () => import("../components/mockups/dashboard-directions/EditorialFinanceDashboard.tsx"),
  "./components/mockups/dashboard-directions/GarageProDashboard.tsx": () => import("../components/mockups/dashboard-directions/GarageProDashboard.tsx"),
  "./components/mockups/dashboard-directions/NeonFleetDashboard.tsx": () => import("../components/mockups/dashboard-directions/NeonFleetDashboard.tsx"),
  "./components/mockups/dashboard-directions/SoftConciergeDashboard.tsx": () => import("../components/mockups/dashboard-directions/SoftConciergeDashboard.tsx")
};
